name: interfaces
on:
  push:
    branches:
    - foolip/webref-sync
jobs:
  sync:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install latest @webref/idl
      run: |
        rm interfaces/*.idl
        tmpdir=`mktemp -d`
        cd $tmpdir
        npm install @webref/idl
        cd -
        mv $tmpdir/node_modules/@webref/idl/*.idl interfaces/
    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: "Sync interfaces/ with @webref/idl"
        commit-message: "Sync interfaces/ with @webref/idl"
        branch: webref/idl
        delete-branch: true
